start_date = (2014, 01, 01)
end_date =   (2018, 12, 23)

symbols = ['NIFTY', 'BHARTIARTL', 'RECLTD'] 

nifty_next_fifty = ['NIFTY', "ABB" ,"ACC" ,"ABCAPITAL" ,"AMBUJACEM" ,"ASHOKLEY" ,"AUROPHARMA" ,"DMART" ,"BANDHANBNK" ,"BANKBARODA" ,"BEL" ,"BHEL" ,"BIOCON" ,"BOSCHLTD" ,"BRITANNIA" ,"CADILAHC" ,"COLPAL" ,"CONCOR" ,"DLF" ,"DABUR" ,"GICRE" ,"GODREJCP" ,"HDFCLIFE" ,"HAVELLS" ,"HINDZINC" ,"ICICIGI" ,"ICICIPRULI" ,"INDIGO" ,"L&TFH" ,"LICHSGFIN" ,"LUPIN" ,"MRF" ,"MARICO" ,"MOTHERSUMI" ,"NHPC" ,"NMDC" ,"OIL" ,"OFSS" ,"PETRONET" ,"PIDILITIND" ,"PEL" ,"PGHH" ,"SBILIFE" ,"SHREECEM" ,"SRTRANSFIN" ,"SIEMENS" ,"SAIL" ,"SUNTV" ,"NIACL" ,"MCDOWELL-N" ,"IDEA" ]


nifty = [ "NIFTY", "ADANIPORTS" , "ASIANPAINT" , "AXISBANK" , "BAJAJ-AUTO" , "BAJFINANCE" , "BAJAJFINSV" , "BPCL" , "BHARTIARTL" , "INFRATEL" , "CIPLA" , "COALINDIA" , "DRREDDY" , "EICHERMOT" , "GAIL" , "GRASIM" , "HCLTECH" , "HDFCBANK" , "HEROMOTOCO" , "HINDALCO" , "HINDPETRO" , "HINDUNILVR" , "HDFC" , "ITC" , "ICICIBANK" , "IBULHSGFIN" , "IOC" , "INDUSINDBK" , "INFY" , "JSWSTEEL" , "KOTAKBANK" , "LT" , "M&M" , "MARUTI" , "NTPC" , "ONGC" , "POWERGRID" , "RELIANCE" , "SBIN" , "SUNPHARMA" , "TCS" , "TATAMOTORS" , "TATASTEEL" , "TECHM" , "TITAN" , "UPL" , "ULTRACEMCO" , "VEDL" , "WIPRO" , "YESBANK" , "ZEEL"]

symbols = nifty
